# Generated by Django 6.1 on 2026-09-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
