# Generated by Django 6.1 on 2026-09-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_photo_alter_education_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.IntegerField(null=True),
        ),
    ]
